from __future__ import annotations

from typing import List

from app.taxonomy.base import ExerciseDef, ExerciseSubset, MovementPattern
from app.taxonomy.muscles import MuscleGroup


EXERCISES: List[ExerciseDef] = [
    # --- Bench press variations ---
    ExerciseDef(
        key="bench_press_barbell_flat",
        name="Barbell Bench Press",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.CHEST],
        secondary_muscles=[MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
        movement_pattern=MovementPattern.PUSH,
        equipment_options=["barbell", "bench"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["compound", "horizontal_press"],
        notes=None,
    ),
    ExerciseDef(
        key="bench_press_dumbbell_flat",
        name="Dumbbell Bench Press",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.CHEST],
        secondary_muscles=[MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
        movement_pattern=MovementPattern.PUSH,
        equipment_options=["dumbbells", "bench"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["compound", "horizontal_press"],
    ),
    ExerciseDef(
        key="bench_press_dumbbell_incline",
        name="Incline Dumbbell Bench Press",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.CHEST],
        secondary_muscles=[MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
        movement_pattern=MovementPattern.PUSH,
        equipment_options=["dumbbells", "bench"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["compound", "incline"],
    ),

    # Pushups
    ExerciseDef(
        key="pushup",
        name="Pushup",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.CHEST],
        secondary_muscles=[MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
        movement_pattern=MovementPattern.PUSH,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=True,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="pushup_clap",
        name="Clap Pushup",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.CHEST],
        secondary_muscles=[MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
        movement_pattern=MovementPattern.PUSH,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=True,
        tags=["plyometric", "explosive", "bodyweight"],
    ),
    ExerciseDef(
        key="pushup_iso_hold",
        name="Pushup Hold",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.CHEST],
        secondary_muscles=[MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
        movement_pattern=MovementPattern.PUSH,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=True,
        tags=["isometric", "bodyweight"],
    ),

    # Pull-ups, rows, etc.
    ExerciseDef(
        key="pullup",
        name="Pull-up",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.BACK],
        secondary_muscles=[MuscleGroup.BICEPS],
        movement_pattern=MovementPattern.PULL,
        equipment_options=["bar", "bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=True,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="chinup",
        name="Chin-up",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.BACK],
        secondary_muscles=[MuscleGroup.BICEPS],
        movement_pattern=MovementPattern.PULL,
        equipment_options=["bar", "bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=True,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="pullup_iso_hold",
        name="Pull-up/Chin-up Hold",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.BACK],
        secondary_muscles=[MuscleGroup.BICEPS],
        movement_pattern=MovementPattern.PULL,
        equipment_options=["bar", "bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=True,
        tags=["isometric", "bodyweight"],
    ),
    ExerciseDef(
        key="lat_pulldown",
        name="Lat Pulldown",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.BACK],
        secondary_muscles=[MuscleGroup.BICEPS],
        movement_pattern=MovementPattern.PULL,
        equipment_options=["cable_machine"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["machine"],
    ),

    # Overhead press & shoulders
    ExerciseDef(
        key="overhead_press_barbell",
        name="Barbell Overhead Press",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.SHOULDERS],
        secondary_muscles=[MuscleGroup.TRICEPS],
        movement_pattern=MovementPattern.PUSH,
        equipment_options=["barbell"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
    ),
    ExerciseDef(
        key="overhead_press_dumbbell",
        name="Dumbbell Overhead Press",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.SHOULDERS],
        secondary_muscles=[MuscleGroup.TRICEPS],
        movement_pattern=MovementPattern.PUSH,
        equipment_options=["dumbbells"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
    ),
    ExerciseDef(
        key="plate_front_raise",
        name="Plate Front Raise",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.SHOULDERS],
        movement_pattern=MovementPattern.OTHER,
        equipment_options=["plate"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=False,
    ),
    ExerciseDef(
        key="plate_side_raise",
        name="Plate Side Raise",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.SHOULDERS],
        movement_pattern=MovementPattern.OTHER,
        equipment_options=["plate"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=False,
    ),
    ExerciseDef(
        key="plate_hold",
        name="Plate Hold",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.SHOULDERS],
        movement_pattern=MovementPattern.OTHER,
        equipment_options=["plate"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=False,
        tags=["isometric"],
    ),

    # Arms
    ExerciseDef(
        key="curl_barbell",
        name="Barbell Curl",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.BICEPS],
        movement_pattern=MovementPattern.PULL,
        equipment_options=["barbell"],
        is_compound=False,
    ),
    ExerciseDef(
        key="curl_dumbbell",
        name="Dumbbell Curl",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.BICEPS],
        movement_pattern=MovementPattern.PULL,
        equipment_options=["dumbbells"],
        is_compound=False,
    ),
    ExerciseDef(
        key="curl_ez_bar",
        name="EZ Bar Curl",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.BICEPS],
        movement_pattern=MovementPattern.PULL,
        equipment_options=["ez_bar"],
        is_compound=False,
    ),
    ExerciseDef(
        key="dip",
        name="Dips",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.TRICEPS],
        secondary_muscles=[MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
        movement_pattern=MovementPattern.PUSH,
        equipment_options=["dip_bars", "bodyweight"],
        allow_bodyweight=True,
        is_compound=True,
    ),
    ExerciseDef(
        key="skull_crusher_ez_bar",
        name="EZ Bar Skull Crushers",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.TRICEPS],
        movement_pattern=MovementPattern.PUSH,
        equipment_options=["ez_bar", "bench"],
        is_compound=False,
    ),
    ExerciseDef(
        key="skull_crusher_dumbbell",
        name="Dumbbell Skull Crushers",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.TRICEPS],
        movement_pattern=MovementPattern.PUSH,
        equipment_options=["dumbbells", "bench"],
        is_compound=False,
    ),
    ExerciseDef(
        key="tricep_pressdown",
        name="Tricep Pressdown",
        subset=ExerciseSubset.UPPER,
        primary_muscles=[MuscleGroup.TRICEPS],
        movement_pattern=MovementPattern.PUSH,
        equipment_options=["cable_machine", "rope_or_bar_attachment"],
        is_compound=False,
    ),

    # --- Core exercises ---
    ExerciseDef(
        key="plank",
        name="Plank",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.UPPER_ABS, MuscleGroup.LOWER_ABS],
        secondary_muscles=[MuscleGroup.OBLIQUES],
        movement_pattern=MovementPattern.CORE_ANTI_ROTATION,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["isometric", "bodyweight"],
    ),
    ExerciseDef(
        key="side_plank",
        name="Side Plank",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.OBLIQUES],
        secondary_muscles=[MuscleGroup.UPPER_ABS, MuscleGroup.LOWER_ABS],
        movement_pattern=MovementPattern.CORE_ANTI_ROTATION,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=True,
        is_compound=False,
        tags=["isometric", "bodyweight"],
    ),
    ExerciseDef(
        key="russian_twist",
        name="Russian Twists",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.OBLIQUES],
        secondary_muscles=[MuscleGroup.UPPER_ABS],
        movement_pattern=MovementPattern.CORE_ROTATION,
        equipment_options=["bodyweight", "plate", "medicine_ball"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["bodyweight", "weighted"],
    ),
    ExerciseDef(
        key="hollow_rock",
        name="Hollow Rocks",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.UPPER_ABS, MuscleGroup.LOWER_ABS],
        movement_pattern=MovementPattern.CORE_FLEXION,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="hollow_hold",
        name="Hollow Hold",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.UPPER_ABS, MuscleGroup.LOWER_ABS],
        movement_pattern=MovementPattern.CORE_FLEXION,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["isometric", "bodyweight"],
    ),
    ExerciseDef(
        key="ab_rollout",
        name="Ab Rollout",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.UPPER_ABS, MuscleGroup.LOWER_ABS],
        secondary_muscles=[MuscleGroup.OBLIQUES],
        movement_pattern=MovementPattern.CORE_ANTI_ROTATION,
        equipment_options=["ab_wheel", "bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="toe_touch",
        name="Toe Touches",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.UPPER_ABS],
        secondary_muscles=[MuscleGroup.LOWER_ABS],
        movement_pattern=MovementPattern.CORE_FLEXION,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="skier",
        name="Skiers",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.OBLIQUES, MuscleGroup.UPPER_ABS],
        movement_pattern=MovementPattern.CORE_ROTATION,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="leg_lift",
        name="Leg Lifts",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.LOWER_ABS],
        secondary_muscles=[MuscleGroup.UPPER_ABS],
        movement_pattern=MovementPattern.CORE_FLEXION,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="flutter_kick",
        name="Flutter Kicks",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.LOWER_ABS],
        secondary_muscles=[MuscleGroup.UPPER_ABS],
        movement_pattern=MovementPattern.CORE_FLEXION,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="bicycle_crunch",
        name="Bicycle Crunches",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.OBLIQUES, MuscleGroup.UPPER_ABS],
        secondary_muscles=[MuscleGroup.LOWER_ABS],
        movement_pattern=MovementPattern.CORE_ROTATION,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="figure_8",
        name="Figure 8s",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.OBLIQUES],
        secondary_muscles=[MuscleGroup.UPPER_ABS, MuscleGroup.LOWER_ABS],
        movement_pattern=MovementPattern.CORE_ROTATION,
        equipment_options=["bodyweight", "medicine_ball"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["bodyweight", "weighted"],
    ),
    ExerciseDef(
        key="roman_chair",
        name="Roman Chairs",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.LOWER_ABS, MuscleGroup.UPPER_ABS],
        movement_pattern=MovementPattern.CORE_FLEXION,
        equipment_options=["roman_chair"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="hanging_leg_lift",
        name="Hanging Leg Lifts",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.LOWER_ABS],
        secondary_muscles=[MuscleGroup.UPPER_ABS],
        movement_pattern=MovementPattern.CORE_FLEXION,
        equipment_options=["pull_up_bar", "bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="knee_to_elbow",
        name="Knee to Elbow",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.OBLIQUES, MuscleGroup.UPPER_ABS],
        secondary_muscles=[MuscleGroup.LOWER_ABS],
        movement_pattern=MovementPattern.CORE_ROTATION,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="palloff_press",
        name="Palloff Press",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.OBLIQUES],
        secondary_muscles=[MuscleGroup.UPPER_ABS, MuscleGroup.LOWER_ABS],
        movement_pattern=MovementPattern.CORE_ANTI_ROTATION,
        equipment_options=["cable_machine"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=False,
        tags=["cable"],
    ),
    ExerciseDef(
        key="landmine",
        name="Landmines",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.OBLIQUES, MuscleGroup.UPPER_ABS],
        secondary_muscles=[MuscleGroup.LOWER_ABS],
        movement_pattern=MovementPattern.CORE_ROTATION,
        equipment_options=["barbell", "landmine_attachment"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=False,
        tags=["weighted"],
    ),
    ExerciseDef(
        key="mountain_climber",
        name="Mountain Climbers",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.UPPER_ABS, MuscleGroup.LOWER_ABS],
        secondary_muscles=[MuscleGroup.OBLIQUES],
        movement_pattern=MovementPattern.CORE_FLEXION,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["bodyweight", "conditioning"],
    ),
    ExerciseDef(
        key="situp",
        name="Situps",
        subset=ExerciseSubset.CORE,
        primary_muscles=[MuscleGroup.UPPER_ABS],
        secondary_muscles=[MuscleGroup.LOWER_ABS],
        movement_pattern=MovementPattern.CORE_FLEXION,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=False,
        tags=["bodyweight"],
    ),

    # --- Lower body exercises ---
    ExerciseDef(
        key="squat_barbell",
        name="Barbell Squat",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.QUADS],
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
        movement_pattern=MovementPattern.SQUAT,
        equipment_options=["barbell"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["compound"],
    ),
    ExerciseDef(
        key="squat_dumbbell",
        name="Dumbbell Squat",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.QUADS],
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
        movement_pattern=MovementPattern.SQUAT,
        equipment_options=["dumbbells"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["compound"],
    ),
    ExerciseDef(
        key="squat_kettlebell",
        name="Kettlebell Squat",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.QUADS],
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
        movement_pattern=MovementPattern.SQUAT,
        equipment_options=["kettlebell"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["compound"],
    ),
    ExerciseDef(
        key="squat_bodyweight",
        name="Bodyweight Squat",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.QUADS],
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
        movement_pattern=MovementPattern.SQUAT,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=False,
        is_compound=True,
        tags=["compound", "bodyweight"],
    ),
    ExerciseDef(
        key="front_squat",
        name="Front Squat",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.QUADS],
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
        movement_pattern=MovementPattern.SQUAT,
        equipment_options=["barbell"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["compound"],
    ),
    ExerciseDef(
        key="deadlift_straight_bar",
        name="Deadlift (Straight Bar)",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
        secondary_muscles=[MuscleGroup.BACK, MuscleGroup.QUADS],
        movement_pattern=MovementPattern.HINGE,
        equipment_options=["barbell"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["compound"],
    ),
    ExerciseDef(
        key="deadlift_trap_bar",
        name="Deadlift (Trap Bar)",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
        secondary_muscles=[MuscleGroup.QUADS, MuscleGroup.BACK],
        movement_pattern=MovementPattern.HINGE,
        equipment_options=["trap_bar"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["compound"],
    ),
    ExerciseDef(
        key="rdl_barbell",
        name="RDL (Barbell)",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
        secondary_muscles=[MuscleGroup.BACK],
        movement_pattern=MovementPattern.HINGE,
        equipment_options=["barbell"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["compound"],
    ),
    ExerciseDef(
        key="rdl_dumbbell",
        name="RDL (Dumbbell)",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
        secondary_muscles=[MuscleGroup.BACK],
        movement_pattern=MovementPattern.HINGE,
        equipment_options=["dumbbells"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["compound"],
    ),
    ExerciseDef(
        key="plyo_lunge_bodyweight",
        name="Plyometric Lunges (Bodyweight)",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.QUADS, MuscleGroup.GLUTES],
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        movement_pattern=MovementPattern.LUNGE,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=True,
        is_compound=True,
        tags=["plyometric", "explosive", "bodyweight"],
    ),
    ExerciseDef(
        key="plyo_lunge_dumbbell",
        name="Plyometric Lunges (Dumbbell)",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.QUADS, MuscleGroup.GLUTES],
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        movement_pattern=MovementPattern.LUNGE,
        equipment_options=["dumbbells"],
        allow_bodyweight=False,
        is_unilateral=True,
        is_compound=True,
        tags=["plyometric", "explosive"],
    ),
    ExerciseDef(
        key="split_lunge_bodyweight",
        name="Split Lunges (Bodyweight)",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.QUADS, MuscleGroup.GLUTES],
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        movement_pattern=MovementPattern.LUNGE,
        equipment_options=["bodyweight"],
        allow_bodyweight=True,
        is_unilateral=True,
        is_compound=True,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="split_lunge_dumbbell",
        name="Split Lunges (Dumbbell)",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.QUADS, MuscleGroup.GLUTES],
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        movement_pattern=MovementPattern.LUNGE,
        equipment_options=["dumbbells"],
        allow_bodyweight=False,
        is_unilateral=True,
        is_compound=True,
    ),
    ExerciseDef(
        key="split_lunge_barbell",
        name="Split Lunges (Barbell)",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.QUADS, MuscleGroup.GLUTES],
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        movement_pattern=MovementPattern.LUNGE,
        equipment_options=["barbell"],
        allow_bodyweight=False,
        is_unilateral=True,
        is_compound=True,
    ),
    ExerciseDef(
        key="walking_lunge",
        name="Walking Lunges",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.QUADS, MuscleGroup.GLUTES],
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        movement_pattern=MovementPattern.LUNGE,
        equipment_options=["bodyweight", "dumbbells"],
        allow_bodyweight=True,
        is_unilateral=True,
        is_compound=True,
        tags=["bodyweight"],
    ),
    ExerciseDef(
        key="belt_squat",
        name="Belt Squat",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.QUADS],
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
        movement_pattern=MovementPattern.SQUAT,
        equipment_options=["belt_squat_machine"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["machine"],
    ),
    ExerciseDef(
        key="explosive_step_up",
        name="Explosive Step Up",
        subset=ExerciseSubset.LOWER,
        primary_muscles=[MuscleGroup.QUADS, MuscleGroup.GLUTES],
        secondary_muscles=[MuscleGroup.HAMSTRINGS],
        movement_pattern=MovementPattern.SQUAT,
        equipment_options=["barbell", "box"],
        allow_bodyweight=False,
        is_unilateral=True,
        is_compound=True,
        tags=["plyometric", "explosive"],
    ),

    # --- Conditioning ---
    ExerciseDef(
        key="rower",
        name="Rower",
        subset=ExerciseSubset.FULL_BODY,
        primary_muscles=[MuscleGroup.BACK, MuscleGroup.QUADS],
        secondary_muscles=[MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.BICEPS],
        movement_pattern=MovementPattern.CARDIO_CONDITIONING,
        equipment_options=["rowing_machine"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["conditioning", "cardio", "machine"],
    ),
    ExerciseDef(
        key="assault_bike",
        name="Assault Bike",
        subset=ExerciseSubset.FULL_BODY,
        primary_muscles=[MuscleGroup.QUADS, MuscleGroup.HAMSTRINGS],
        secondary_muscles=[MuscleGroup.GLUTES, MuscleGroup.SHOULDERS],
        movement_pattern=MovementPattern.CARDIO_CONDITIONING,
        equipment_options=["assault_bike"],
        allow_bodyweight=False,
        is_unilateral=False,
        is_compound=True,
        tags=["conditioning", "cardio", "machine"],
    ),
]

